## Dispersal and the random-walk

### 1. Random walk for 1 individual

a\) Write your own code to simulate an individual random walk. Assume that the starting point is always $(x,y) =(0,0)$ and the probability of an individual to choose any direction (i.e. left, right, up or down) is the same. It should be a function taking as argument the number of steps and returning a list of two vectors, one with the $x$ positions over time and another with the $y$ positions overtime.

b\) Plot the random walks of several individuals on the same graph, using at least 5,000 steps for each individual.

### 2. Random walk for several ($n$) individuals

a\) Write your own code to simulate random walks for $n$ individuals and return the final position of each individual. The function should take the number of individuals and the number of time steps as arguments and return a list containing two vectors: one with the final x -coordinate of each individual and another with the final y -coordinate of each individual.

b\) Create histograms showing the distributions of the final $x$ - and $y$ -coordinates of 10,000 individuals after 10, 100 and 1,000 time steps.

c\) Create a function that takes a vector of values, `xlast`, a mean value, `meanx`, and a standard deviation, `stdx`, as arguments, and returns the log-likelihood of observing those values given those parameters.

d\) Find the values `meanx` and `stdx` that maximize the likelihood of the observations. Are these values the same as `mean(xlast)` and `std(xlast)`? Explain why.

e\) **Extra credit:** Create histograms showing the distribution of the distance from the origin $$sqrt(x^2+y^2)$$ for the final positions of 10,000 individuals after 10, 100, 1000 and 10000 time steps. How does the mean distance relate to the length of the random walk? Fit a Rayleigh distribution, $$\left(\frac{r}{\sigma^2}\right) e^{-r^2/(2 \sigma^2)}$$ to each histogram using non-linear fitting, and overlay the fitted distributions on the corresponding graphs.
